### ISSUE TITLE
괄호로 묶인 문자열의 처리 오류

### ISSUE THREAD

**Issue by kjsman** [entrylabs/entryjs#1028]
# Summary
엔트리에서 문자열이 괄호로 묶여있는 경우, 여러 문제를 일으키게 됩니다.

# Description
```python
import Entry

def when_start():
    Entry.print("(test)".replace("(test)", "abcd"))
```

이 엔트리파이썬 코드를 실행하면(블럭코딩으로 전환해도 똑같이 됩니다), `abcd`가 출력되어야 정상입니다. 그러나, 실제는 그렇게 실행되지 않습니다. `(abcd)`로 출력됩니다.

**Comment by ViresseNisSJ** [comment]
안녕하세요.
엔트리파이선 Entry.print("(test)".replace("(test)", "abcd")) 작성시, abcd가 출력되도록 수정되었습니다.
*11/1(목) 반영
감사합니다.
