### ISSUE TITLE
Sprite Modal 부분은 공개가 안된것인가요

### ISSUE THREAD

**Issue by shl0122** [entrylabs/entryjs#1280]
어떠한 다른 버전을 빌드해봐도 Sprite나 Pictuer부분은 보이질 않네요 ㅠ
엔트리 사이트 html에는 Modal Class가 존재하는데, Git에 공개하신 여러개의 버전들을 
빌드해봤지만 "Modal" 클래스가 없던데 혹시 내부사항에 따른 부분인가요..?
현재 entry-tool.js 도 정상적으로 불러왔는데, 오브젝트 추가를 누르면 따로 오류 뜨는건 없고 개발자 도구에 commandType 210 addObjectButtonClick 도 뜨는데, 창에 아무 변화가 없네요 .. !

**Comment by extracold1209** [comment]
@shl0122 

Sprite Modal 이 오브젝트 추가하기 팝업을 말씀하시는건가요?

entryjs 는 확인하신바와 같이 해당 이벤트를 dispatch 하기만 합니다.
해당 팝업의 경우 엔트리 웹에서 직접 구현한 부분입니다.
팝업 형태는 entry-tool 에서 구현되어있습니다만 entryjs 에서 dispatch 된 이벤트를 통해 팝업을 띄우는 로직은 내부코드로 보셔야 할 것 같습니다.

entryjs 에서 event dispatch
-> entry web 에서 이벤트를 받고, 오브젝트 추가하기 화면 띄움
-> 선택시 서버에 가지고있는 오브젝트를 가져와 entryjs 에 주입

과 같은 방식을 가지고 있습니다.
이와 같은 동작을 정상적으로 확인해보고 싶으시다면, 엔트리의 오프라인 프로젝트인  https://github.com/entrylabs/entry-offline 에서 코드를 확인해보실 수 있습니다.

**Comment by shl0122** [comment]
빠르고 정확한 답변 감사합니다 (__)!

**Comment by extracold1209** [comment]
@shl0122 

네. 팝업을 생성하는 부분은 entry-tool에 구현되어있지만, entryjs 와 연동하여 데이터를 주입하는 전체 로직은 공개되어있지 않습니다.  
하지만 오프라인 프로젝트의 [workspace.jsx](https://github.com/entrylabs/entry-offline/blob/9af436698c2459b71d36d1ed112192a880ebfa5e/src/renderer/components/workspace.jsx#L107-L109) 부분이 운영 페이지와 거의 동일하므로 이쪽을 확인해보세요.

**Comment by shl0122** [comment]
네 감사합니다!
근 2년째 오픈소스를 통해 경험을 쌓고있는데, 늘 존경합니다 ^^7 
언젠가 뵐수있는날이 오면 좋겠네요 !
