### ISSUE TITLE
변경된 것인가요?

### ISSUE THREAD

**Issue by hayanggames** [entrylabs/entryjs#1325]
1. 옛날에는 entryjs 빌드하면 블록도 같이 있으니까 다시 빌드 해보니 없네요. 제 컴퓨터가 이상한 것인가요? 아니면 변경된 것인가요?

2. 만약 변경된 것이라면 이유가 무엇인가요?

3. 만약 변경된 것이 맞다면 entry-offline 빌드했을 때 블록이 안 뜨는 것은 변경된 것 때문인가요?

**Comment by extracold1209** [comment]
@hayanggames 
- 블록 로드 구조에 대해서는 변경된 점이 없습니다.
- 어떤 이슈인지 전혀 알수가 없습니다.

**Comment by hayanggames** [comment]
@extracold1209 이렇게 뜨는 것이 맞나요?
![](https://user-images.githubusercontent.com/45326612/58951051-275c9300-87cb-11e9-8fb8-7c116e12cd78.png)
