### ISSUE TITLE
Speak Block

### ISSUE THREAD

**Issue by enemali** [entrylabs/entryjs#1597]
How can i use the speak and say block. i tried it it does not work. can you guide me on how to make the speak block speakout sound

**Comment by extracold1209** [comment]
@enemali 

Do you mean 'speak and say block'  below picture?

![image](https://user-images.githubusercontent.com/40051225/73053099-32834100-3eca-11ea-9d18-33062af31d21.png)

or this?

![image](https://user-images.githubusercontent.com/40051225/73053210-76764600-3eca-11ea-9741-39e57a242eb9.png)

---

these red blocks that mean 'float a speech bubble over the current object' like this

![image](https://user-images.githubusercontent.com/40051225/73053356-dd93fa80-3eca-11ea-8f94-5ffe034a2afd.png)

the block thread is created as below

![image](https://user-images.githubusercontent.com/40051225/73053390-f3a1bb00-3eca-11ea-8321-a12f5f83856e.png)

---

and, green block is actually sounds.  
default sound file is bark sound.

do you want to add your sound file?

**Comment by enemali** [comment]
The red block is what i meant . In addition to the "speech bubble" , i will like it to speak it out . that is text to speech , i tried the extention but it did not work.
![entry](https://user-images.githubusercontent.com/17222224/73069306-a95e1100-3ead-11ea-9ac6-9770037676f4.PNG)

**Comment by enemali** [comment]
The red block is what i meant . In addition to the "speech bubble" , i will like it to speak it out . that is text to speech , i tried the extention but it did not work.
![entry](https://user-images.githubusercontent.com/17222224/73069306-a95e1100-3ead-11ea-9ac6-9770037676f4.PNG)

**Comment by enemali** [comment]
The red block is what i meant . In addition to the "speech bubble" , i will like it to speak it out . that is text to speech , i tried the extention but it did not work.
![entry](https://user-images.githubusercontent.com/17222224/73069306-a95e1100-3ead-11ea-9ac6-9770037676f4.PNG)

**Comment by extracold1209** [comment]
@enemali 

hmm...  
'Say block' do make object's speech bubble.  
'Speech to text extension block' does speak the real sound that you write and it works when I tested.

as far as I understand, I think you want to combine the two functions into one block.
or.. you mean you want to just use speech to text block but it doesn't work your browser?

**Comment by enemali** [comment]
i am using the speech block on the desktop ( offline ) version window10. could that be a problem ? 
Do i need to use the online version to make the speech sound?

**Comment by extracold1209** [comment]
@enemali 

no, it doesn't matter. offline also can use speech block if you connected to network.

can you test [online version](https://playentry.org/ws)?

if you can use that block on online version, it maybe offline code issue.  
in that case, run offline version and put ctrl + shift + delete to open devtool.  
and execute speech block, show me console page.

**Comment by enemali** [comment]
Thanks for answering my questions, it works when my computer is connected to the internet , when the computer is offline , the speech block **does not** work. Can we have an offline speech block? because my students dont have internet in school

**Comment by extracold1209** [comment]
@enemali 

unfortunately, extension blocks are not available unless you are connected to the Internet for now. sorry
because all extension blocks work through external APIs.

the second best is, add a few sound files into entry workspace, play sound when a certain variable is entered.

**Comment by enemali** [comment]
Thanks for your time i really appreciate.
Lastly do you know the part of the sourcecode that connects to the External speech APi?

**Comment by extracold1209** [comment]
@enemali 

https://github.com/entrylabs/entryjs/blob/develop/src/playground/blocks/block_ai_utilize_tts.js

This file is related to TTS.

API is to Entry's back-end server and actually server uses [NAVER's API](https://www.ncloud.com/product/aiService/css)
