### ISSUE TITLE
npm이 이상해요

### ISSUE THREAD

**Issue by salam1028** [entrylabs/entryjs#1677]
npm install도 했습니다
npm serve라고쓰면 로그에 이렇게 뜹니다
> entry-js@0.1.1 serve D:\entry\entryjs-develop (1)\entryjs-develop
> cross-env NODE_ENV=serve webpack-dev-server --open --hot --inline --host 127.0.0.1

clean-webpack-plugin: D:\entry\entryjs-develop (1)\entryjs-develop\dist has been removed.
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1211:19)
    at listenInCluster (net.js:1276:12)
    at doListen (net.js:1415:7)
    at processTicksAndRejections (internal/process/task_queues.js:74:11)
Emitted 'error' event at:
    at emitErrorNT (net.js:1255:8)
    at processTicksAndRejections (internal/process/task_queues.js:74:11) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! entry-js@0.1.1 serve: `cross-env NODE_ENV=serve webpack-dev-server --open --hot --inline --host 127.0.0.1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the entry-js@0.1.1 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\for\AppData\Roaming\npm-cache\_logs\2020-02-29T11_58_30_575Z-debug.log
사이트에 들어가면
500 Servlet Exception
javac compiler is not available in Java(TM) SE Runtime Environment 1.8.0_231-b11.
Check that you are using the JDK, not the JRE.
Resin/4.0.62 Server: 'app-0'
 Exception
javac compiler is not available in Java(TM) SE Runtime Environment 1.8.0_231-b11.
Check that you are using the JDK, not the JRE.
Resin/4.0.62 Server: 'app-0'
이렇게 뜨고요
디버그 파일에는
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'serve'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.5.0
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle entry-js@0.1.1~preserve: entry-js@0.1.1
6 info lifecycle entry-js@0.1.1~serve: entry-js@0.1.1
7 verbose lifecycle entry-js@0.1.1~serve: unsafe-perm in lifecycle true
8 verbose lifecycle entry-js@0.1.1~serve: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\entry\entryjs-develop (1)\entryjs-develop\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;D:\새 폴더 (5)\bin;D:\새 폴더 (5)\utils\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Live\Shared;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Users\for\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\for\AppData\Local\Programs\Python\Python36\;C:\Users\for\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Bandizip\;C:\Users\for\AppData\Roaming\npm;D:\Microsoft VS Code\bin;C:\Program Files\JAVA\jdk-10.0.1\bin;;C:\Program Files (x86)\ESTsoft\ALSee\x64
9 verbose lifecycle entry-js@0.1.1~serve: CWD: D:\entry\entryjs-develop (1)\entryjs-develop
10 silly lifecycle entry-js@0.1.1~serve: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'cross-env NODE_ENV=serve webpack-dev-server --open --hot --inline --host 127.0.0.1'
10 silly lifecycle ]
11 silly lifecycle entry-js@0.1.1~serve: Returned: code: 1  signal: null
12 info lifecycle entry-js@0.1.1~serve: Failed to exec serve script
13 verbose stack Error: entry-js@0.1.1 serve: `cross-env NODE_ENV=serve webpack-dev-server --open --hot --inline --host 127.0.0.1`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:200:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:200:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid entry-js@0.1.1
15 verbose cwd D:\entry\entryjs-develop (1)\entryjs-develop
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
18 verbose node v12.5.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error entry-js@0.1.1 serve: `cross-env NODE_ENV=serve webpack-dev-server --open --hot --inline --host 127.0.0.1`
22 error Exit status 1
23 error Failed at the entry-js@0.1.1 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
이렇게 뜹니다.
해결법이 없을까요?

**Comment by extracold1209** [comment]
다른데서 이미 8080 번 포트를 사용중인것으로 보입니다.

**Comment by salam1028** [comment]
@extracold1209 8080포트 다 닫았습니다. 그런데도 그러네요
