### ISSUE TITLE
npm run serve를 하고 들어가니 오류가 뜹니다

### ISSUE THREAD

**Issue by swoo5571** [entrylabs/entryjs#1678]
로그에는
ERROR in ./src/entry.js
Module not found: Error: Can't resolve 'core-js/fn/object/values' in 'C:\Users\레비브륄\Desktop\entryjs-develop\entryjs-develop\src'
 @ ./src/entry.js 24:0-35
이렇게 뜨면서 버튼이 눌려지지 않습니다.

**Comment by extracold1209** [comment]
음.. core-js 을 로드해야하는데, package.json 에 명시가 되어있지를 않네요. 이부분은 확인해봐야겠네요.

yarn add -D core-js 와 같이 core-js 를 추가해주시거나,
src/entry.js 의 `require('core-js/fn/object/values');` 구문을 삭제해보시기 바랍니다.
