### ISSUE TITLE
eslint , Codacy/PR Quality Review 관련

### ISSUE THREAD

**Issue by pillpill** [entrylabs/entryjs#1685]
Pull Requests 를 요청하면 
eslint 와 
Codacy/PR Quality Review 로 코드 검증 진행과정에서 나온 문제를 해결하지 못하여 문의합니다.

여러가지 문제는 해결하였으나 
문자열 ' 작은 따옴표와  " 큰 따옴표의 표시방식에 문제가 발생합니다.

eslint 에서는 작은 따옴표로 하라고 하고 큰 따옴표는 에러로 표시합니다.
Codacy/PR Quality Review  에서는 큰 따옴표로 하라고 하고 작은따옴표로 표시한건 에러로 
표시합니다.

어떻게 바꾸든 한쪽에서 에러로 표시하는데 어떻게 해력해야 할지 모르겠습니다.
검토 부탁드립니다.

**Comment by extracold1209** [comment]
@pillpill eslint 를 기준으로 작업해주시면 됩니다. eslint 가 개발시 가장 최신 컨벤션으로 조정되고 있습니다.

**Comment by pillpill** [comment]
eslint 기준으로 수정하여 업로드 하였습니다.

PR Workflow / eslint (pull_request) Successful in 1m  

Codacy/PR Quality Review — Not up to standards. This pull request quality could be better.

PR Quality Review 에서 문제가 발행하였고

메세지 내용은 
Strings must use doublequote.
'use strict';

Strings must use doublequote.
id: '3A.2',

이런식으로 모든 문자를 doublequote 로 하라는 메세지가 나옵니다.

어떤방향으로 해야할지 모르겠습니다. 도움 부탁드립니다.

**Comment by extracold1209** [comment]
@pillpill 

Codacy 혹은 린트는 문제가 있다 하더라도 머지에는 지장이 없습니다.
크게 개의치 않으셔도 되며, 컨벤션은 린트를 기준으로 하기 때문에 일단 Codacy 에서 발생하는 에러는 무시하셔도 됩니다.

추후 기존 eslint 컨벤션과 동일한 룰로 수정하도록 하겠습니다.

**Comment by pillpill** [comment]
네 감사합니다.
