### ISSUE TITLE
npm 오류

### ISSUE THREAD

**Issue by salam1028** [entrylabs/entryjs#1739]
분명 8080포트를 사용하는 프로그램이 없는데 실행이 안됩니다. 80 포트도 혹시나 영향이 갈까봐 강제종료했는데 안됩니다. 관리자 권한으로 cmd를 실행도 하였습니다.
오류내용
clean-webpack-plugin: D:\entry\entryjs-develop (1)\entryjs-develop\dist has been removed.
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1211:19)
    at listenInCluster (net.js:1276:12)
    at doListen (net.js:1415:7)
    at processTicksAndRejections (internal/process/task_queues.js:74:11)
Emitted 'error' event at:
    at emitErrorNT (net.js:1255:8)
    at processTicksAndRejections (internal/process/task_queues.js:74:11) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! entry-js@0.1.1 serve: `cross-env NODE_ENV=serve webpack-dev-server --open --hot --inline --host 127.0.0.1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the entry-js@0.1.1 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\for\AppData\Roaming\npm-cache\_logs\2020-04-09T00_42_35_225Z-debug.log

**Comment by extracold1209** [comment]
@salam1028 

혹시 다른 포트 사용 / 관리자 권한으로 실행

해보셨나요?

**Comment by salam1028** [comment]
@extracold1209 다른포트사용은 하는법을 모르고 관리자 권한으로 실행은 했습니다

**Comment by extracold1209** [comment]
@salam1028 다른포트로도 한번 확인해보시기 바랍니다. 

https://github.com/entrylabs/entryjs/blob/develop/webpack_config/serve.js

에서 수정하실 수 있습니다.
