### ISSUE TITLE
포트를 바꿨는데도 안됩니다.

### ISSUE THREAD

**Issue by salam1028** [entrylabs/entryjs#1765]
> entry-js@0.1.1 serve D:\entry\entryjs-develop (1)\entryjs-develop
> cross-env NODE_ENV=serve webpack-dev-server --open --hot --inline --host 127.0.0.1

clean-webpack-plugin: D:\entry\entryjs-develop (1)\entryjs-develop\dist has been removed.
i ｢wds｣: Project is running at http://127.0.0.1:8181/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from ./
i ｢wds｣: 404s will fallback to /index.html
i ｢wdm｣: wait until bundle finished: /
i ｢wdm｣: wait until bundle finished: /
i ｢wdm｣: wait until bundle finished: /
i ｢wdm｣: wait until bundle finished: /
[BABEL] Note: The code generator has deoptimised the styling of D:\entry\entryjs-develop (1)\entryjs-develop\src\playground\blocks\hardware\block_roboid.js as it exceeds the max of 500KB.
일괄 작업을 끝내시겠습니까 (Y/N)?
라고 뜨네요. (몇번 다시 접속함) 다시하니 화면은 나오고 버튼은 안눌리고 로그가 바뀌었습니다
× ｢wdm｣: Hash: 6ac3a7dd4c128a74766b
Version: webpack 4.41.6
Time: 34980ms
Built at: 2020-04-20 19:17:51
        Asset       Size  Chunks                   Chunk Names
         0.js   14.9 KiB       0  [emitted]
     0.js.map   16.7 KiB       0  [emitted] [dev]
    entry.css    133 KiB   entry  [emitted]        entry
entry.css.map    167 KiB   entry  [emitted] [dev]  entry
     entry.js   8.95 MiB   entry  [emitted]        entry
 entry.js.map   10.5 MiB   entry  [emitted] [dev]  entry
   index.html    5.4 KiB          [emitted]
manifest.json  242 bytes          [emitted]
Entrypoint entry = entry.css entry.js entry.css.map entry.js.map
[0] multi (webpack)-dev-server/client?http://127.0.0.1:8181 (webpack)/hot/dev-server.js ./src/entry.js 52 bytes {entry} [built]
[./node_modules/simplebar/dist/simplebar.css] 39 bytes {entry} [built]
[./node_modules/webpack-dev-server/client/index.js?http://127.0.0.1:8181] (webpack)-dev-server/client?http://127.0.0.1:8181 4.29 KiB {entry} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {entry} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {entry} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {entry} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {entry} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {entry} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {entry} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {entry} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {entry} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {entry} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {entry} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {entry} [built]
[./src/entry.js] 4.92 KiB {entry} [built]
    + 756 hidden modules

ERROR in ./src/entry.js
Module not found: Error: Can't resolve 'core-js/fn/object/values' in 'D:\entry\entryjs-develop (1)\entryjs-develop\src'
 @ ./src/entry.js 24:0-35
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./example/example.ejs] 6.07 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
Child mini-css-extract-plugin ../../entryjs-develop (1)\entryjs-develop\node_modules\css-loader\dist\cjs.js??ref--7-1!../../entryjs-develop (1)\entryjs-develop\node_modules\postcss-loader\src\index.js??postcss!../../entryjs-develop (1)\entryjs-develop\node_modules\less-loader\dist\cjs.js??ref--7-3!../../entryjs-develop (1)\entryjs-develop\node_modules\simplebar\dist\simplebar.css:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js?!./node_modules/postcss-loader/src/index.js?!./node_modules/less-loader/dist/cjs.js?!./node_modules/simplebar/dist/simplebar.css] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--7-3!./node_modules/simplebar/dist/simplebar.css 3.11 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/dist/runtime/api.js] 2.46 KiB {mini-css-extract-plugin} [built]
Child mini-css-extract-plugin ../../entryjs-develop (1)\entryjs-develop\node_modules\css-loader\dist\cjs.js??ref--7-1!../../entryjs-develop (1)\entryjs-develop\node_modules\postcss-loader\src\index.js??postcss!../../entryjs-develop (1)\entryjs-develop\node_modules\less-loader\dist\cjs.js??ref--7-3!../../entryjs-develop (1)\entryjs-develop\src\css\entry.less:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js?!./node_modules/postcss-loader/src/index.js?!./node_modules/less-loader/dist/cjs.js?!./src/css/entry.less] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--7-3!./src/css/entry.less 130 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/dist/runtime/api.js] 2.46 KiB {mini-css-extract-plugin} [built]
i ｢wdm｣: Failed to compile.
가 추가되었습니다.... 도와주세요 ㅜ

그리고 계속 이슈를 작성하는데도 불구하고, 도와주시는 분들께 진심으로 감사드립니다.

**Comment by extracold1209** [comment]
@salam1028 

`npm install core-js` 명령어 실행 후 재시도 한번 해보시겠어요?

**Comment by salam1028** [comment]
@extracold1209 알겠습니다.

**Comment by salam1028** [comment]
@extracold1209 [BABEL] Note: The code generator has deoptimised the styling of D:\entry\entryjs-develop (1)\entryjs-develop\src\playground\blocks\hardware\block_roboid.js as it exceeds the max of 500KB.
× ｢wdm｣: Hash: 6ac3a7dd4c128a74766b
Version: webpack 4.41.6
Time: 48801ms
Built at: 2020-05-18 13:40:22
        Asset       Size  Chunks                   Chunk Names
         0.js   14.9 KiB       0  [emitted]
     0.js.map   16.7 KiB       0  [emitted] [dev]
    entry.css    133 KiB   entry  [emitted]        entry
entry.css.map    167 KiB   entry  [emitted] [dev]  entry
     entry.js   8.95 MiB   entry  [emitted]        entry
 entry.js.map   10.5 MiB   entry  [emitted] [dev]  entry
   index.html    5.4 KiB          [emitted]
manifest.json  242 bytes          [emitted]
Entrypoint entry = entry.css entry.js entry.css.map entry.js.map
[0] multi (webpack)-dev-server/client?http://127.0.0.1:8181 (webpack)/hot/dev-server.js ./src/entry.js 52 bytes {entry} [built]
[./node_modules/simplebar/dist/simplebar.css] 39 bytes {entry} [built]
[./node_modules/webpack-dev-server/client/index.js?http://127.0.0.1:8181] (webpack)-dev-server/client?http://127.0.0.1:8181 4.29 KiB {entry} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {entry} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {entry} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {entry} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {entry} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {entry} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {entry} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {entry} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {entry} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {entry} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {entry} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {entry} [built]
[./src/entry.js] 4.92 KiB {entry} [built]
    + 756 hidden modules

ERROR in ./src/entry.js
Module not found: Error: Can't resolve 'core-js/fn/object/values' in 'D:\entry\entryjs-develop (1)\entryjs-develop\src'
 @ ./src/entry.js 24:0-35
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./example/example.ejs] 6.07 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
Child mini-css-extract-plugin ../../entryjs-develop (1)\entryjs-develop\node_modules\css-loader\dist\cjs.js??ref--7-1!../../entryjs-develop (1)\entryjs-develop\node_modules\postcss-loader\src\index.js??postcss!../../entryjs-develop (1)\entryjs-develop\node_modules\less-loader\dist\cjs.js??ref--7-3!../../entryjs-develop (1)\entryjs-develop\node_modules\simplebar\dist\simplebar.css:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js?!./node_modules/postcss-loader/src/index.js?!./node_modules/less-loader/dist/cjs.js?!./node_modules/simplebar/dist/simplebar.css] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--7-3!./node_modules/simplebar/dist/simplebar.css 3.11 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/dist/runtime/api.js] 2.46 KiB {mini-css-extract-plugin} [built]
Child mini-css-extract-plugin ../../entryjs-develop (1)\entryjs-develop\node_modules\css-loader\dist\cjs.js??ref--7-1!../../entryjs-develop (1)\entryjs-develop\node_modules\postcss-loader\src\index.js??postcss!../../entryjs-develop (1)\entryjs-develop\node_modules\less-loader\dist\cjs.js??ref--7-3!../../entryjs-develop (1)\entryjs-develop\src\css\entry.less:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js?!./node_modules/postcss-loader/src/index.js?!./node_modules/less-loader/dist/cjs.js?!./src/css/entry.less] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--7-3!./src/css/entry.less 130 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/dist/runtime/api.js] 2.46 KiB {mini-css-extract-plugin} [built]
i ｢wdm｣: Failed to compile. 설치후에도 이런현상이 발생합니다.

**Comment by salam1028** [comment]
@extracold1209 npm WARN acorn-jsx@5.1.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\karma\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ core-js@3.6.5
updated 1 package and audited 1469 packages in 37.292s
found 895 vulnerabilities (875 low, 18 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New minor version of npm available! 6.9.0 -> 6.14.5       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.14.5   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯ 
설치 완료후 나온 로그입니다

**Comment by salam1028** [comment]
npm 업데이트 후에는, 500 Servlet Exception
javac compiler is not available in Java(TM) SE Runtime Environment 1.8.0_231-b11.
Check that you are using the JDK, not the JRE.
Resin/4.0.62 Server: 'app-0' 라는 문구가 사이트에 뜨면서 안됩니다.

**Comment by extracold1209** [comment]
현재 최신버전에서는 core-js/fn 이 아닌 core-js/stable 로 변경되었는데요. 코드 버전을 최신으로 올려보세요

**Comment by salam1028** [comment]
@extracold1209 업데이트를 해봤는데 블록모드와 파이썬모드가 안됩니다

**Comment by extracold1209** [comment]
@salam1028 

안된다의 기준이 바뀐것 같은데, 현재 상황이 어떤 상태인가요? 어디까지 정상동작하며,
어떤 콘솔에러가 발생하는건지 자세하게 알려주셔야 합니다.

더불어, 어디까지나 yarn serve 스크립트로 실행되는 코드는 workspace only 이며, 엔트리 웹사이트에서 제공하는 기능 전반이 제공되지 않을 수 있습니다.
