### ISSUE TITLE
[ ] 키를 눌렀을때 코드가 제대로 작동하지 않습니다

### ISSUE THREAD

**Issue by genius0412** [entrylabs/entryjs#1869]
e.keyCode 또는 e.which 를 사용중이신것 같은데
e.key 를 사용하면 되지 않을까요
그러면 keyInputList 도 지워도 될 것 같은데요

**Comment by extracold1209** [comment]
@wodnjs6512 

해당 이슈 개발 중 관련 이슈가 있었나요?

**Comment by genius0412** [comment]
네 맞습니다
혹시 "[] 키를 눌렀을때" 블록의 코드가 어디 있나요?

**Comment by genius0412** [comment]
정확하게 버그를 말씀드리자면
드랍다운 부분을 클릭하고 'home' 키 등을 클릭하면
"대상없음" 이라고 뜨면서 'home' 키를 눌렀을때 실제로 실행이 됩니다

**Comment by genius0412** [comment]
감사합니다.
