### ISSUE TITLE
알티노 라이트 블록 출력 관련

### ISSUE THREAD

**Issue by maru-shlee** [entrylabs/entryjs#1972]
안녕하세요. 
새로운 디바이스 추가를 위해서 develop-hw 브랜치에서 작업을 하고 있습니다.
hardware에 신규 파일을 추가하고 하드웨어 id는 저희 기존 id에 값을 올려 사용하고 있습니다(24.3).
하드웨어 연결 여부와 상관없이 하드웨어 탭에 "알티노라이트"의 블록이 보이고 있습니다.
isNotFor 값도 제대로 지정이 되어있는듯 한데요... 확인 부탁드립니다.

**Comment by maru-shlee** [comment]
그리고 제가 추가한 블록들은 연결이 되면 아래에 추가로 생깁니다.

**Comment by maru-shlee** [comment]
자세히 보니
name: 'altino_lite' 으로 되어있는데
isNotFor: ['altino lite'] 로 되어있었네요...

**Comment by wodnjs6512** [comment]
@maru-shlee 현재 이기웅님은 퇴사하신 관계로 제가 담당하고 있는데요 해당 부분은 이슈를 발견 하셨다면 수정해서 PR부탁드립니다.

**Comment by maru-shlee** [comment]
@wodnjs6512 제가 올린 소스 코드가 아니라서 엔트리 담당자 분이 직접 수정하시는게 좋을 것 같은데 상관 없나요?

**Comment by maru-shlee** [comment]
@wodnjs6512 다른 업체에서 올린 소스코드에 버그가 있어 수정이 필요한 것입니다.

**Comment by wodnjs6512** [comment]
@maru-shlee 
어떠한 방식이든 수정하셔서 바로 올려주셔야합니다. 
저희가 수정하는것에는 한계가 있고, 저희쪽에서 업체측의 코드에 개입할수는 없습니다.
특정 업체의 코드에 대해서 저희쪽에 수정 요청을 하는것이 맞지 않다고 생각됩니다.
오늘내로 수정 PR을 주시지 않거나 어떠한 방식으로든 해결이 안되는 경우에는 이번 배포에 제외될 예정입니다

**Comment by wodnjs6512** [comment]
@maru-shlee 
일단 저희 배포 일정상 이번에는 제가 수정해서 올려두겠지만 앞으로는 저희쪽에 코어 로직 관련 문의가 아닌 하드웨어 코드 수정을 요청하시는 것은 도와드리기 어렵습니다.

**Comment by wodnjs6512** [comment]
@maru-shlee 
수정 하여 머지 하였기에 이슈 클로즈 하겠습니다.
