### ISSUE TITLE
[Feature request] initOptions에 확장, 인공지능, 데이터 분석 블럭메뉴와 테이블 탭을 제거할 수 있는 옵션제공 

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entryjs#1996]
안녕하세요? 개도국(우즈베키스탄)을 위한 커스텀 버전을 만들고 있습니다.

최신버전에 탑재된 확장, 인공지능, 데이터 분석 블럭메뉴와 테이블 탭을 제거할 수 있는 옵션제공해 주시면 감사합니다.
한국에서만 사용가능한 기능이 대부분이고, 기능이 너무 많아 오히려 현지에서 어려운 프로그램으로 인식되기도 해 필요에 따라 넣고 뺄 수 있으면 좋겠습니다.

감사합니다.

**Comment by wodnjs6512** [comment]
@JeongJun-Lee 
확장/ 인공지능은 옵션을 추가하려고 하고, 데이터 분석 탭은 제거 옵션 곧 추가 될 예정입니다. 추가되는대로 코멘트 남기겠습니다.

**Comment by wodnjs6512** [comment]
@JeongJun-Lee 
Entry.init 에서 두번째 파라미터에서 아래의 옵션들을 추가하여 주시면 해당 블럭들이 표시 되지 않도록 할 수 있습니다.
https://github.com/entrylabs/entryjs/blob/a8fcc405a626e09ff39e9e25f5aa2870e98c427c/src/util/init.js#L212

dataTableDisable: true,
expansionDisable: true,
aiUtilizeDisable: true,

**Comment by JeongJun-Lee** [comment]
옵션 제공해 주셔서 감사합니다. expensionDisable을 특정 사용언어(예를들어 베트남어 등) 선택시 그 때만 안보이게 할 수 있는 옵션이 있는지요? 해당 기능은 한국 전용이라 다른 나라에선 의미가 없어서요.

**Comment by kimorkim** [comment]
@JeongJun-Lee 
다국어 변경과정에서 Entry.init을 다시 하는 과정에서 option을 조정하시면 될것 같습니다.
답변이 늦어서 죄송합니다.
의견 감사합니다.
