### ISSUE TITLE
하드웨어 아두이노 확장으로 연결 후 해당 블럭의 버저음 13번째 '도'에서 에러발생

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entryjs#2071]
하드웨어 아두이노 확장으로 연결 후 해당 블럭의 버저음 13번째 '도'의 경우 맵핑되는 값이 실제 소스상이 없으므로 에러발생!
![image](https://user-images.githubusercontent.com/11474775/118027128-04559900-b37b-11eb-8bf3-6214fc87d9ca.png)
![image](https://user-images.githubusercontent.com/11474775/118027674-9fe70980-b37b-11eb-8b92-d65eb4265219.png)

**Comment by kimorkim** [comment]
@JeongJun-Lee 오류 제보 감사합니다. 다음 배포 때 처리하겠습니다.
