### ISSUE TITLE
함수생성시 '판단값'을 파라미터로 연결시 undefined로 표시되는 이슈

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entryjs#2074]
함수생성시 '판단값'을 파라미터로 연결시 undefined로 표시되는 이슈. 연결 하는 순간 저렇게 됨!

![image](https://user-images.githubusercontent.com/11474775/118136185-46cfb200-b41d-11eb-8309-5c37c1e6d3fa.png)

**Comment by wodnjs6512** [comment]
@JeongJun-Lee 이 이슈는 해결 되었습니다. 이슈 close하겠습니다.
![스크린샷 2021-07-08 오전 9 57 11](https://user-images.githubusercontent.com/2320526/124846014-e1d6a980-dfd2-11eb-8297-3f3c3ff6327d.png)
