### ISSUE TITLE
블럭 -> 파이썬 변경 후 다시 파이썬 -> 블럭 으로 변경되지 않음 (실제 변경이 되었으나, UI상 코드 에디터창 상태 그대로 남아있음)

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entryjs#2075]
1. 아래와 같은 함수를 이용해 코딩 후
![image](https://user-images.githubusercontent.com/11474775/118136618-bd6caf80-b41d-11eb-9651-b47d7af7b3ca.png)
![image](https://user-images.githubusercontent.com/11474775/118136809-f4db5c00-b41d-11eb-8ac0-f848d6055c85.png)

2. 블럭->파이썬 변환
![image](https://user-images.githubusercontent.com/11474775/118136956-176d7500-b41e-11eb-96aa-cf3986a62091.png)
![image](https://user-images.githubusercontent.com/11474775/118137035-2c4a0880-b41e-11eb-916e-a667766ccdaf.png)

3. 파이썬->블록 변환
![image](https://user-images.githubusercontent.com/11474775/118137124-484daa00-b41e-11eb-9f43-542fd6b68a35.png)
블록 카테고리 상에 블록들이 파이썬 블록이 아닌, 일반 블록인 관계로 블록모드로 변경은 된 것으로 보이나, UI상은 에디터 그대로 남아있음!!!

**Comment by wodnjs6512** [comment]
@JeongJun-Lee 
이슈 남겨 주신것이 파이썬에서 ->블럭으로 변환시 문자/숫자값으로 변환된것이 다시 파이썬으로 변환되었을때 바로잡아져 있어야된다는 의미일까요?

**Comment by wodnjs6512** [comment]
@JeongJun-Lee 
판단값이 있는 경우에만 그런것으로 보이네요 다른 케이스는 발견하신것이 없을까요?
