### ISSUE TITLE
[질문] 모양, 사운드 추가

### ISSUE THREAD

**Issue by morishjs** [entrylabs/entryjs#2095]
안녕하세요.

모양, 사운드 추가 버튼을 눌러도 반응이 없습니다. playentry 홈페이지 네트워크 탭에서 에셋들의 주소를 보니 에셋서버에서 mp3 파일이나 각종 파일들을 내려받는 걸 미루어봤을 때 에셋서버가 필요해보이는데, 맞을까요?

**Comment by wodnjs6512** [comment]
@morishjs 모양, 사운드 추가버튼 관련 기능은 entry-tool 에 있는 기능을 사용합니다. 해당 부분에 대해서 패키지 추가후에 작업을 진행하셔야합니다.
