### ISSUE TITLE
이름 입력 창에서 xss 문제

### ISSUE THREAD

**Issue by ddtt786** [entrylabs/entryjs#2287]
만들기의 모든 이름 입력 창에서 img 태그를 이용하여 xss를 할 수 있습니다.
![image](https://user-images.githubusercontent.com/69110424/169679490-e22fabdd-2b1b-4c53-b100-84ba5db51de1.png)
(eval을 사용하지 않아도 작동)

**Comment by EntryFireRun** [comment]
생각해보면 안막아도 돼는(?)

**Comment by lemonbbt** [comment]
사실 막아야 되는(?)
