### ISSUE TITLE
[문의] 하드웨어 블록에 대응하는 파이썬 함수를 만들고자 하는데 관련한 가이드 문서가 있는지요?

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entryjs#2303]
안녕하세요? 하드웨어 블록에 대응하는 파이썬 함수를 만들고자 하는데 관련한 가이드 문서를 찾을 수가 없어서요.

블록명세(https://docs.playentry.org/guide/entryjs/2016-05-22-add_new_blocks.html)에서 언급되어야 할 것으로 보이는데  파이썬 함수를 추가하기 위한 syntax->py 부분을 어떻게 작성하는지 안내해 주시면 감사합니다. 

또한, 파이썬 코딩시 추가된 함수들이 이처럼 coding assistance 에서 나오게 하려면 어떤 등록절차가 필요한 것인지요?

![image](https://user-images.githubusercontent.com/11474775/172711619-b681ac63-4a03-446d-9e93-b69a964a334e.png)

감사합니다.

**Comment by Tnks2U** [comment]
@JeongJun-Lee 
안녕하세요. 현재 엔트리 파이썬은 하드웨어에 관련해서는 대응하고 있지 않습니다. 엔트리 파이썬 사용에 대한 가이드나 별도 cs대응이 어려운 점 양해 부탁드립니다.
