### ISSUE TITLE
Can I create the english version of the Readme File.

### ISSUE THREAD

**Issue by ArslanYM** [entrylabs/entryjs#2465]
Will help a lot of people

**Comment by Tnks2U** [comment]
@ArslanYM 
I'm sorry for the late reply.
If you make a ReadMe file and give PR, we will check the contents and decide whether to merge or not.
If there is no big problem with quality, we will review it positively.
Thank you for your interest in entry.

**Comment by ArslanYM** [comment]
Will start working on it.

**Comment by ArslanYM** [comment]
@Tnks2U I have added a PR, please review it.

**Comment by Tnks2U** [comment]
Thank you very much. I will send it to the team members and review it.
