### ISSUE TITLE
엔트리파이썬/블럭 코딩 함수 내 블럭 변환 문제

### ISSUE THREAD

**Issue by SuhJae** [entrylabs/entryjs#2565]
# 문제
아래와 같이 테스트용 함수와, 시작하기 버튼을 누르면 이 함수를 호출하는 작품이 있습니다.

![image](https://github.com/entrylabs/entryjs/assets/90325840/cdc1c5c7-6298-42c7-8e2b-b2ce6938ab26)

이를 엔트리 파이썬으로 변환하면 함수 내 모든 코드가 삭제되는 오류가 있습니다. (아래 gif 참고)

![Screen Recording 2023-09-19 at 7 43 39 PM](https://github.com/entrylabs/entryjs/assets/90325840/34c8b6f1-c357-45fd-8bfa-755d7612faac)

# 환경

브라우저: Firefox 117.0.1 (Arm64)
OS: macOS 13.5.2 (22G91)

위 캡쳐와 별도로 크롬 (117.0.5938.88 Arm64), 사파리 (16.6 (18615.3.12.11.2)) 에서도 테스트 해보았으나, 같은 문제가 확인 되었습니다.

# 관련 콘솔 로그

**함수 추가**
```
commandType 1001 funcEditStart entry.js:255028:15
```

**함수 추가 완료**
```
commandType 1002 funcEditEnd entry.js:255028:15
```

**블럭 ,코딩을 파이썬으로 변환 시**
```
action 
Array [ "엔트리파이썬", "setPythonMode" ]
 true [id]-3434e6f05b4896d4.js:1:8081
```

**Comment by JeongJun-Lee** [comment]
해당 커밋을 pull 하시면, 해결됩니다.

https://github.com/JeongJun-Lee/entryjs/commit/94bfae655613d9a0615a4abfcfa053e53922e257

**Comment by kimorkim** [comment]
@SuhJae 
제보 감사합니다

@JeongJun-Lee 
답변 감사합니다.
