### ISSUE TITLE
yarn serve 에러입니다.

### ISSUE THREAD

**Issue by codable-choi** [entrylabs/entryjs#2586]
Node 버전 : 14.15.0

yarn serve
yarn run v1.22.19
$ cross-env NODE_ENV=serve webpack-dev-server --open --hot --inline --host 127.0.0.1      
[webpack-cli] Error: Unknown option '--inline'
[webpack-cli] Run 'webpack --help' to see available commands and options
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by oopchoi72** [comment]
다른 분들은 잘 되시나요? 웹팩 버전을 바꾸거나 스크립트를 바꿔야 에러가 사라지는데 설정 파일을 바꿔서 PR 할수도 없고.. 어떻게들 하고 계신지 궁금합니다.

**Comment by kimorkim** [comment]
안녕하세요. 제보감사합니다.
엔트리팀에서는 최대한 node의 LTS버전을 따라하기위해 빌드를 수정하고 있으며,
이번에는 node 버전이 18로 올라감에 따라 webpack 버전도 변경되었습니다.
이 과정에서 저희가 수정한 버전이 develop 브랜치에 정상적으로 코드가 반영되어 있지 않음을 확인하였습니다.
이에 수정 완료처리하여 `yarn serve`가 가능하도록 수정 처리되었습니다.

혹시 추가로 사용해보시고 문제 있으시면 말씀주세요.

참고로 현재 권장하는 node버전은 18.18.2(LTS) 입니다.
