### ISSUE TITLE
[하드웨어] 마이크로비트 통신 관련 오류 

### ISSUE THREAD

**Issue by gray-rabbit** [entrylabs/entryjs#2604]
https://github.com/entrylabs/entryjs/blob/a99df23aab8a7a6f0fb69d31c5f924d835e4980a/src/playground/blocks/hardware/block_microbit2.js#L1826C15-L1826C55

마이크로비트 통신을 위한 코드에서 해당 블럭은 인자가 1개이지만 2개의 인자를 받으며 두번째 값을 사용함으로 인해 통신채널이 항상 0으로 지정되는 문제가 있습니다. 

물론 이 코드를 수정해도 통신은 원활하게 이루어지지 않습니다. 

마이크로비트의 통신을 원할하게 하려면 어떻게 해야하나요? 펌웨어는 microbit2-lite 를 사용하였습니다. 
혹시 펌웨어코드를 볼 수 있는 곳이 있나요?

**Comment by Tnks2U** [comment]
'브라우저로 연결하기' 기능으로 펌웨어를 다운로드 하시면, hex파일을 받아보실 수 있습니다. 펌웨어는 https://python.microbit.org/v/3 에서 작성되었습니다.
