### ISSUE TITLE
yarn serve 이후 오류

### ISSUE THREAD

**Issue by emillly25** [entrylabs/entryjs#2650]
yarn 명령어 이후
yarn_serve 를 했을때,

<e> [webpack-dev-server] [HPM] Error occurred while proxying request 127.0.0.1:8080/entry.css?cdc5f0899b6796a4756f to http://localhost:8080/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
<e> [webpack-dev-server] [HPM] Error occurred while proxying request 127.0.0.1:8080/entry.js?cdc5f0899b6796a4756f to http://localhost:8080/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)

와 같은 오류가 나옵니다. 
네트워크 탭에서는 504에러로 뜨는데 어떤 문제일까요?

**Comment by emillly25** [comment]
proxy관련 문제로 해결함

**Comment by piaojongwien** [comment]
어떻게 해결하셧나요?
