### ISSUE TITLE
함수 블럭에서 메모리 누수 발생

### ISSUE THREAD

**Issue by ChessBot-Entry** [entrylabs/entryjs#2652]
function_general, function_value 블럭을 실행할 때마다 생성되는 executor가, 함수가 즉시 종료될 경우 제거되지 않아 메모리 누수를 일으킵니다. (아마 removeExecutor가 실행되지 않는 것과 관련이 있는 것 같습니다)

**Comment by kimorkim** [comment]
반영되어 close합니다.
