### ISSUE TITLE
불필요한 async 삭제

### ISSUE THREAD

**Issue by Navi-Labs** [entrylabs/entryjs#2665]
https://github.com/entrylabs/entryjs/blob/703d3a00338264a0817cf11b15df2e5d2ed54898/src/playground/blocks/block_calc.js#L2537-L2542
https://github.com/entrylabs/entryjs/blob/703d3a00338264a0817cf11b15df2e5d2ed54898/src/playground/blocks/block_calc.js#L2583-L2587

두 블록 `change_rgb_to_hex`, `change_hex_to_rgb`에서
await 구문을 쓰지 않음에도 함수가 async로 정의됨
promise가 리턴되어 executor에서 1틱씩 딜레이가 발생함

**Comment by kimorkim** [comment]
@Navi-Labs 
제보 감사합니다.
