### ISSUE TITLE
(소리)저장중이라는 전체화면 오버레이 팝업에서 앱 멈춰있는 현상

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entryjs#2674]
증상: (소리)저장중이라는 전체화면 오버레이 팝업에서 앱 멈춰있는 현상

재현경로: 새로 오브젝트 추가 -> 소리 추가 -> 편집 후 저장

로그:
<img width="547" alt="image" src="https://github.com/entrylabs/entryjs/assets/11474775/84e1b823-7a75-4afd-89ca-109823d88dff">

원인:  this.object가 null
<img width="1066" alt="image" src="https://github.com/entrylabs/entryjs/assets/11474775/ac4f96ee-4416-4e86-84f5-f7ac77e0a878">

**Comment by kimorkim** [comment]
@JeongJun-Lee 
안녕하세요. 일단 오류코드를 봐서는 entryjs 이슈가 아니라 offline 이슈로 보입니다.
최근 sound editor 기능에 대응하기 위해 offline에 ffmpeg 설치 기능이 들어 간것과 관련한 관련된 오류로 보이는데요.
패키지 설치는 잘되셨을까요?

**Comment by JeongJun-Lee** [comment]
@kimorkim 네 설치는 잘되어 있습니다. 맥/원도우즈에서 모두 동일한 오류가 발생합니다.

**Comment by kimorkim** [comment]
@Tnks2U 
체크 가능 하실까요?

**Comment by JeongJun-Lee** [comment]
electron-builder.json의 설정에서 다음과 같이 ffmpeg과 ffprobe를 asar.unpack처리하면 해결이 되긴하네요. 업무에 참고하세요. @Tnks2U 

![image](https://github.com/entrylabs/entryjs/assets/11474775/bc2ddb85-495d-45bb-9287-b3cbb9c95b54)
