### ISSUE TITLE
영어환경에서도 계산 카테고리의 요일값이 한글로 표기되는 문제

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entryjs#2676]
증상: 영어환경에서도 계산 카테고리의 요일값이 한글로 표기되는 문제

원인: 코드에 요일이 한글값으로 고정되어 있음
<img width="585" alt="image" src="https://github.com/entrylabs/entryjs/assets/11474775/4cd033d3-4ae4-4bc1-8ea4-1228be5938a2">

**Comment by kimorkim** [comment]
@JeongJun-Lee 
내부 논의 결과 getDay로 바로 처리해서 숫자 값 [0, 1, 2, 3, 4, 5, 6] 이 나오도록 블록스펙을 조정하였습니다.
이슈 제보 감사합니다.

**Comment by JeongJun-Lee** [comment]
@kimorkim 안녕하세요? 네 잘 처리되었다니 다행입니다. 죄송하지만, 이 오프라인쪽 이슈(https://github.com/entrylabs/entry-offline/issues/198) 좀 봐주실 수 있을까요? 제 쪽에서는 dev빌드와 실행에는 전혀 문제 없는데, prod 빌드하면 빌드까지는 되지만 막상 실행에서 문제가 생기고 있습니다. 네이버쪽에서는 같은 코드를 가지고 빌드와 실행까지 잘되시니까 정상 릴리즈를 주기적으로 하고 계신 것으로 이해되고, 그래서, 빌드환경구축 이슈가 아닌가 생각되는데 제 빌드환경을 어떻게 구축해야 할지요?
