### ISSUE TITLE
해당 버전 빌드가 진행되지 않습니다.

### ISSUE THREAD

**Issue by JH-Kim88** [entrylabs/entryjs#2769]
node.js에서 16.20.2, 18.20.3,  20.14.0, 22.2.0과 nvm으로 node.js버전+16.19.0, 18.16.0, pnpm 등 다양하게 시도 해서 테스트를 진행했는데 18 버전 이하에서는 빌드 시 18버전 이상을 사용하라고 나와 18버전 이상을 사용하면 빌드는 성공적이지만 아래 그림 처럼 엔트리 이미지가 나오지 않습니다. 인터넷에서 찾아보면 node 16이하에서 사용하라고 나오는거 같은데 node 16은 빌드가 webpack 플러그인 때문에 18 버전 이상을 사용하라고만 나옵니다. 
혹시나 제 PC에서 문제인가 해서 windows11 아무것도 설치되지 않는 환경에서 가이드 내용대로만 해서 테스트를 해도 동일한 결과가 나왔습니다. linux PC에서도 동일한 오류가 발생했습니다.
어떻게 진행해야 할까요?
<img width="1517" alt="yarn serve 오류" src="https://github.com/entrylabs/entryjs/assets/83936495/869c3cf9-e4a3-4572-bacf-509579c71d72">

**Comment by LIMT-KR** [comment]
혹시 이거 어떻게 해결하셨는지 알 수 있을까요?? 저도 같은 이유로 작동이 안 되고 있어서요.
