### ISSUE TITLE
 EntryVideoLegacy is not defined,  Entry.init is not a function

### ISSUE THREAD

**Issue by Jin-YJ** [entrylabs/entryjs#2867]
프로젝트 Fork후 실행시 example.ejs에서 init을 찾을 수 없음과 EntryVideoLegacy를 못가져오는데, 해당 가이드가 있을까요? 

기존 프로젝트에서 변경사항은 serve.js에서 proxy부분을 localhost -> 127.0.0.1 로 변경하였습니다.

그외에 현재 사용하는 노드 버전등이 있다면 알려주시면 감사합니다

**Comment by kimorkim** [comment]
기본적인 example 및 사용에 대한 문서는 아래의 링크를 확인해 주세요.
[개발문서](https://docs.playentry.org/entryjs/)
[example](https://github.com/entrylabs/example)

노드버전은 꾸준히 최신화 하고 있고, entryjs 한정으로 node 20을 사용하셔도 무방합니다.

**Comment by Jin-YJ** [comment]
1. https://docs.playentry.org/guide/basic/setting_environment.html 해당 가이드 참조하여 환경세팅을 하였는데, entryjs를 serve로 실행하여 example.ejs를 호출 하였을때 위의 두가지 라이브러리를 못가져 오는 것으로 보여집니다. serve.js에서 호출하는 ejs부분을 따로 작성해야 하는 걸까요??
2. 올려주신 example은 따로 fork하여 entryjs와 연동 해야하는건가요? 활용 예를 모르겠습니다.

**Comment by kimorkim** [comment]
@Jin-YJ 
일단 entryjs 활용 목적이 하드웨어 블록 개발을 위해서 이신가요?
하드웨어 개발문서가 최신화는 아니라서 몇가지 요소가 빠져 있을것 같은데요. 제가 링크드린 개발문서는 전반적인 entryjs의 세팅이 담겨 있습니다.
(하드웨어도 이와 같은 세팅으로 진행가능합니다.)

example 레포지토리는 example.ejs의 본격적인 버전이라고 생각하시면 됩니다.
EntryVideoLegacy를 가져오는 부분도 포함되어 있습니다.

다만, 하드웨어 블록만 개발하려고 하시는거라면 과한 내용일수 있어서, 일단 develop 브랜치에 해당부분 수정해서 push 했습니다.
develop을 다시 받아서 보시거나 변경사항을 보시고 그대로 적용하시면 될것 같습니다.

https://github.com/entrylabs/entryjs/commit/7f560603df4d67d426f468320d5c6c182bec77cf

**Comment by Jin-YJ** [comment]
해결됐습니다 감사합니다
