### ISSUE TITLE
entry-mini 빌드시 에러

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entryjs#846]
안녕하세요? 

가이드(https://entrylabs.github.io/)를 통해서는 엔트리와 엔트리 미니의 차이를 명확하게는 이해하지 못했습니다.실과형 개발이라고만 언급하셨는데 실과라는게 교과서 실과 과목을 말씀하시는 건지, 그리고 실과 서버라는 것은 또 무슨 용도인지 명확하게 이해할 수 없었습니다. 가능하시면 문서를 보강해 주시면 명확하게 이해할 수 있을 것 같습니다.

아무튼 저에게는 전체 엔트리에 모든 기능이 다 필요하기 보다, 컴팩트한 버전이 더 나을 것 같아, mini라는 이름이 그런게 아닌가 싶어 엔트리 미니로 빌드를 시도해 보았습니다.
즉 가이드(https://entrylabs.github.io/docs/guide/entry-mini/2016-12-12-getting_started.html)에 나와 있는데로 feature/offline_mini 브랜치 체크아웃 해서 npm i 로 dependencies 설치 후에 grunt를 실행했습니다.

Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "karma" not found. Used --force, continuing.

라는 메시지가 나오면서 빌드가 바로 종료됩니다. 무엇이 문제일까요?

**Comment by kimorkim** [comment]
안녕하세요.

엔트리 미니는 현재 사이트에서 운영되는 교과형을 테스트하기 위해 짧게 운영된 버전이며,
오프라인 1.6.0 이 나온 11월 30일 이후로 더이상 사용되지 않은 버전입니다.

그리고 karma는 테스트 과정이기 때문에 karma와 관련된 내용은 무시하셔도 좋습니다.
다른 이유로 빌드가 안된다고 한다면 추가적인 다른 로그가 필요한 상태입니다.

엔트리 미니에 포함되었던 내용은 이미 master브랜치와 develop브랜치에 이미 포함되었기 때문에
더이상 관리 되지 않은 미니버전은 확인하지 않으셔도 됩니다.

이상입니다.

**Comment by JeongJun-Lee** [comment]
그럼, 말씀해주신 최신 내용으로 가이드 문서 업데이트 해주시면 시작하는 개발자들에게 큰 도움이 되겠네요.

그리고, entryjs 마스터 브랜치에서 빌드는 위와 같은 에러없이 성공적으로 이뤄졌습니다. 그럼, 빌드 결과를 테스트 하기 위해서는 example/example.html을 실행시키면 되는 것인지요? 실행시켜봤는데 전체 기능이 다 동작되는거 같지 않은데 예를들어 메뉴 중에 오브젝트 추가하기 버튼을 눌러, 새로운 오브젝트를 추가하고 싶은데 눌러도 아무 반응이 없고, 또 최초 화면에 위치한 오브젝트의 크기를 변경하기 위해 오브젝트 사방으로 눌러싸인 사이즈 조절 점을 당겨봐도 아무런 변화가 없습니다. 이 상태가 정상적인 상태인지 궁금합니다.

감사합니다.

**Comment by kimorkim** [comment]
@JeongJun-Lee 네 해당 상태가 정상적인 상태입니다.
해당 example.html은 블록의 실행만을 확인하기 위한 테스트 샘플 페이지 이며
나머지 구현은 서비스 구현이고 서비스 코드는 외부에 공개되지 않았습니다.
해당 기능을 구현하고 싶으시다면, entry-offline 레포지토리를 확인해보시기 바랍니다.
(참고로 해당 개발 문서는 따로 존재하지는 않습니다.)

**Comment by JeongJun-Lee** [comment]
지금 당장 새로운 기능 구현 쪽을 추가하고 싶다기 보다 우선은 커스텀 오브젝트 같은 것들(단순 이미지가 아닌, 애니매이션이 가능하도록 몇 가지 모양을 등록해 하나로 만든)을 등록시켜 활용해 보고 싶은데요. 어떻게 등록하고 호출해 검증해보는 것이 가능할런지요? entryjs말고 오프라인 버전에 추가해 검증할 수 있단 말로 이해되었지만, 오프라인 버전엔 빌드하는 방법 조차 안내가 안되어 있어서 검증이 가능할지 모르겠습니다. 감사합니다.

**Comment by JeongJun-Lee** [comment]
웹서버를 이용해 온라인 플랫폼 서비스를 구현하는 코드는 비공개 되어도 좋을 것 같습니다. 

다만, 스크래치 오프라인 버전처럼 웹 서비스와 상관없이 독립적으로 동작이 가능해 스스로 코딩 공부를 할 수 있는 엔트리 오프라인 버전에 경우는 더 오픈 소스화 되어서 스크래치처럼 더 글로벌 하게 확산되기를 바라고 있습니다. 개인적으로 스크래치 오프라인 버전보다 엔트리 오프라인 버전에 장점이 더 많다고 생각하기 때문에 충분히 가능성이 있다고 생각합니다.

엔트리를 개발하고 주관하고 계신 곳이 비영리 공공의 목적으로 특별히 대상은 아이들을 위한 교육 플랫폼으로 알고 있는데, 저희 나라의 이 좋은 프로젝트가 글로벌 사회에 더 좋은 일에 더 쓰이게 될 수 있기를 바라고 있습니다. 그렇게 되기 위해선 이왕이면 인터넷 인프라가 좋고 모든 것이 넉넉한 환경에서 공부하는 아이들도 중요하지만, 전 세계라는 큰 그림 속에 아이들의 상황을 바라보면, 대부분의 아이들은 인터넷 인프라가 열악하고 있어도 인터넷 이용 가격이 너무 비싸서 대부분의 일반 가정에서는 인터넷을 이용할 수 없는 이곳 개발도상국 같은 곳에 사는 아이들의 숫자가 훨씬 더 많다는 것입니다.

저는 이곳 개발 도상국에서 봉사 요원으로 일하면서 틈틈이 이곳 아이들에게도 코딩 교육을 하려고 하고 있습니다. 스크래치 오프라인 버전을 쓰려고 했다가 그것 보다 장점이 더 많은 우리 나라의 자랑스런 엔트리란 툴을 사용하고자 합니다. 다만, 이곳에 아이들의 현지 실정에 맞게 오프라인 버전을 지역화해서 사용하고 싶은데 결국 지역 언어와 지역 컨텐츠(지역민들에게 친숙한 그림 오브젝트들)를 넣은 지역어 버전을 만드는 것입니다. 제가 이곳 개발 도상국에서 시작할 수 있도록 오프라인 버전을 더욱더 오픈 소스화와 문서화 해주실 수 있으신지요? 그럼 답변 기다리겠습니다.

감사합니다.

**Comment by kimorkim** [comment]
@JeongJun-Lee 
안녕하세요.
저희도 오프라인개발에 대한 문서화에 많은 부분 공감을 하고 있는 상태입니다.
하지만 문서화 작업이 시간이 걸리는 작업이고, 작업 할 수 있는시간이 많지는 않아서 
작업이 쉽게 진행되고 있지 못하는 상태입니다.
그래도 저희쪽에서도 문서화에 대한 필요성을 느끼고 있는 만큼 조만간 작업을 시작할 예정이며,
아마 다음달 내에는 문서화가 진행되지 않을까 합니다.

**Comment by JeongJun-Lee** [comment]
공감해 주시고 문서화 계획이 잡혀있고 시작하신다니 좋은 소식 감사합니다. 시간을 내지 못할 정도로 바쁜 업무로 열심히 일하시는데 건강 관리도 잘하셔서 늘 건강하게 지내셨으면 좋겠습니다. 그럼, 문서화 때까지 기다리면서 저는 틈틈히 지역어 번역을 먼저 시작해야 겠네요.
